import type { Metadata } from "next";
import "./globals.css";
import { MobileNavbar } from "@/components/navbar/MobileNavbar";
import { DesktopNavbar } from "@/components/navbar/DesktopNavbar";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`w-[100dvw] h-[100dvh] m-0 p-0`}
      >
        <div className="w-full h-full bg-[#F1F5F9] dark:bg-[#0F172A] scrollbar-custom">
          <div className="w-full h-[100px] hidden sm:flex justify-center py-4">
            <DesktopNavbar />
          </div>
          <main className="w-full sm:h-[calc(100%-100px)] h-[calc(100%-70px)] overflow-y-auto">{children}</main>
          <div className="w-full h-[70px] sm:hidden">
            <MobileNavbar />
          </div>
        </div>
      </body>
    </html >
  );
}
