import type { Metadata } from "next";
import "./globals.css";
import { MobileNavbar } from "@/components/navbar/MobileNavbar";
import { DesktopNavbar } from "@/components/navbar/DesktopNavbar";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export const metadata: Metadata = {
  title: "Kunal Bera | Frontend-Focused Full Stack Developer",
  description:
    "Portfolio of Kunal Bera — a frontend-focused full stack developer crafting scalable, high-performance web applications with Next.js, TypeScript, and Tailwind CSS. Explore my projects, experience, and AI-driven solutions.",
  keywords: [
    "Kunal Bera",
    "Frontend Developer Portfolio",
    "Full Stack Developer",
    "Next.js Developer",
    "React Developer",
    "Angular Developer",
    "JavaScript Developer",
    "TypeScript Developer",
    "HTML Developer",
    "CSS Developer",
    "HTML CSS Developer",
    "Tailwind CSS Developer",
    "Modern UI Developer",
    "Responsive Web Design",
    "Web Performance Optimization",
    "AI-Powered Web Apps",
    "Interactive UI Engineer",
    "SaaS Frontend Engineer",
    "Enterprise Web Applications",
    "Frontend Engineer Mumbai",
    "Next.js Portfolio Website",
    "UI/UX Focused Developer"
  ],

  authors: [{ name: "Kunal Bera" }],
  creator: "Kunal Bera",
  openGraph: {
    title: "Kunal Bera | Frontend-Focused Full Stack Developer",
    description:
      "Crafting intuitive, scalable, and AI-driven web experiences using Next.js, TypeScript, and Tailwind CSS.",
    url: "https://built-by-kunal.vercel.app",
    siteName: "Kunal Bera Portfolio",
    type: "website",
    images: [
      {
        url: "public/images/kunal_3D_image.png", // replace this with your actual OG image path
        width: 1200,
        height: 630,
        alt: "Preview of Kunal Bera’s Portfolio Website"
      }
    ]
  }
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`w-[100dvw] h-[100dvh] m-0 p-0`}
      >
        <div className="w-full h-full bg-[#F1F5F9] dark:bg-[#0F172A] scrollbar-custom">
          <div className="w-full h-[100px] hidden sm:flex justify-center py-4">
            <DesktopNavbar />
          </div>
          <main className="w-full sm:h-[calc(100%-100px)] h-[calc(100%-70px)] overflow-y-auto">{children}</main>
          <div className="w-full h-[70px] sm:hidden">
            <MobileNavbar />
          </div>
        </div>
      </body>
    </html >
  );
}
